language: python
sudo: false
dist: xenial  # Avoid https://code.djangoproject.com/ticket/30055#comment:12
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# Add JS tests
matrix:
  include:
    - name: "JS tests"
      language: node_js
      install: npm ci
      node_js:
        - 8
      script:
        - npm run check
        - npm test

install:
  # tox-travis automatically splits the jobs
  - pip install tox-travis

script:
  - tox
