name: Run JS tests and quality control

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node: [12, 14, 16]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node JS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node}}
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: |
        npm run check
        npm test
        npm run build
