name: Run python tests and quality control

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox wheel
        sudo apt-get install gettext
    - name: Explicitly install build_requires for python 3.5
      run: pip install setuptools_webpack Babel
      if: ${{ matrix.python == 3.5 }}
    - name: Run tests
      run: |
        tox
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
